name       : nautilus-share
version    : 0.7.3
release    : 5
source     :
    - git|https://gitlab.gnome.org/GNOME/nautilus-share.git : 583236846b7b0b46b4aacc76fb5632ac44d62747
license    : GPL-2.0-or-later
component  : network.clients
summary    : Nautilus extension to share folder using Samba
description: |
    Nautilus Share allows you to quickly share a folder from the GNOME Nautilus
    file manager without requiring root access.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnautilus-extension)
rundeps    :
    - samba
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
