name       : nautilus-share
version    : 0.7.5
release    : 9
source     :
    - https://gitlab.gnome.org/coreyberla/nautilus-share/-/archive/0.7.5/nautilus-share-0.7.5.tar.bz2 : 708e10e379e09907802ec4afbcffa310d03877d0bc167d01d9d0a5eb3b4f9cbc
license    : GPL-2.0-or-later
component  : network.clients
summary    : Nautilus extension to share folder using Samba
description: |
    Nautilus Share allows you to quickly share a folder from the GNOME Nautilus
    file manager without requiring root access.
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libnautilus-extension-4)
rundeps    :
    - samba
setup      : |
    %patch -p1 < $pkgfiles/nautilus-share-lang-fix.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
